queue_rules:
  - name: default
    speculative_checks: 5
    conditions: []

pull_request_rules:
  - name: merge using merge queue
    conditions:
      - base=main
      - check-success=doSomething
    actions:
      queue:
        name: default
