name: test

on: 
  pull_request:
  merge_group:

jobs:
  doSomething:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          x=1
          while [ $x -le 20 ]
          do
            echo -n "PR2 $x "
            date            
            x=$(( $x + 1 ))
            sleep 1
          done